---
apiVersion: v2
appVersion: 0.5.0-beta
description: Family media library manager with Home Assistant and Music Assistant integration
name: music-library
version: 1.0.4
kubeVersion: ">=1.16.0-0"
keywords:
  - music-library
  - music
  - home-assistant
  - music-assistant
  - media
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/music-library
icon: https://raw.githubusercontent.com/AntorFr/music-library/main/app/static/logo.png
sources:
  - https://github.com/AntorFr/music-library
  - https://ghcr.io/antorfr/music-library
maintainers:
  - name: AntorFr
    email: antor.music-library@users.noreply.github.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
